### ISSUE TITLE
RevTube: Rewritten ROADMAP

### ISSUE THREAD

**Issue by jkosixtyfour** [cosmixcode/revtube-rewritten#1]
Hey everyone! This is a list of things that we plan to add. This includes things like accounts for example, due to this being a new project.
Keep in mind this list _is unfinished_.

- [ ] SQL/PHP
  - [ ] Accounts
  - [ ] Videos
  - [ ] ~~Music~~
  - [ ] Comments
  - [ ] RevTube Studio
  - [ ] Edit video metadata
  - [x] ~~Upload videos from here aswell~~
  - [x] ~~Customize channel~~
- [ ] User interface
  - [ ] Login/signup
  - [ ] Home page and all videos page
  - [ ] Watch page
  - [ ] Channel page/channel list
  - [ ] Settings
  - [ ] Upload
  - [ ] All comments page

**Comment by AzaleaBlossom** [comment]
who claims i am the one
